### ISSUE TITLE
[bug] Config update to 7.7.2-20210602 failed

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#1304]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.5.1
zwave-js version: 7.7.1

### Describe the bug

Updating the device config files fails.

There are also some usability issues with the update process. When you click the Install button, the dialog closes but the notification is still apparent, and you can install many times in parallel.

```
2021-06-03T23:09:26.634Z DRIVER   Installing version 7.7.2-20210602 of configuration DB...
2021-06-03T23:09:38.087Z DRIVER   Installing version 7.7.2-20210602 of configuration DB...
```

The update process is fairly opaque, maybe this is a node-zwave-js problem, but there is no indication of what's going on. Running on my RPi4, it consumes all the CPU and disk I/O. Is it expected that config file updates are so resource intensive? Is this because I'm running on the aarch64 arch? It took 6 mins to see the failure.

### To Reproduce

1. Click Install in the Device Config updates
2. Watch zwave-js logs for failure

### Expected behavior

The update succeeds.

I should not be allowed to issue multiple Installs at the same time, it should be disabled while one is in progress.

### Additional context

Here are the zwave-js logs:
```
2021-06-03T22:56:34.634Z DRIVER   Checking for configuration updates...
2021-06-03T22:56:34.792Z DRIVER   Configuration update available: 7.7.2-20210602
2021-06-03T22:56:38.305Z DRIVER   Installing version 7.7.2-20210602 of configuration DB...
2021-06-03T23:02:31.526Z DRIVER   Config update failed: Package manager exited with code 1
                                  warning Resolution field "@zwave-js/config@7.7.2-20210602" is incompatible wit
                                  h requested version "@zwave-js/config@7.7.1"
                                  error https://registry.yarnpkg.com/prettier-standard/-/prettier-standard-16.4.
                                  1.tgz: ESOCKETTIMEDOUT
                                  error https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT
                                  warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 ||
                                  ^5.0.0".
                                  warning "prettier-standard > prettierx > @typescript-eslint/typescript-estree
                                  > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-de
                                  v || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-
                                  beta || >= 3.7.0-dev || >= 3.7.0-beta".
                                  error An unexpected error occurred: "ENOENT: no such file or directory, open '
                                  /usr/local/share/.cache/yarn/v6/npm-prettier-standard-16.4.1-964e7e3f3029427ab
                                  8e01bdffb72dea9a87f62c8-integrity/node_modules/prettier-standard/.yarn-metadat
                                  a.json'".
```

Here are the zwavejs2mqtt logs, it seems to think it was successful?
```
z2m        | 2021-06-03 15:56:38.173 INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
z2m        | 2021-06-03 16:02:31.528 INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```

**Comment by mwav3** [comment]
I had the same issue.  The config update fails. Worse, the failed update attempt appears to corrupt the whole program and it won't come back up after restarting the container.  It generated a bunch of log errors when trying to restart after the failed update. I also Tried a blank install and it failed to import the old settings.json file, and failed to update the config. Im using Docker and Tried to use a volume, also local folder mapping,  and tried setting the environment variable to the config path and nothing made it work. Rolled back to the prior version and no issues.  I'll try and post some logs let me know if you need anything else about the install.

**Comment by kpine** [comment]
The error:
```
z2m        |  ______                       _     ___                  _   _
z2m        | |___  /                      (_)   |__ \                | | | |
z2m        |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
z2m        |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
z2m        |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
z2m        | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
z2m        |                             _/ |                      | |
z2m        |                            |__/                       |_|
z2m        | Error: Could not locate the bindings file. Tried:
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/build/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/build/Debug/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/build/Release/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/out/Debug/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/Debug/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/out/Release/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/Release/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/build/default/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/compiled/15.11.0/linux/arm64/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
z2m        |  → /usr/src/app/node_modules/@serialport/bindings/lib/binding/node-v88-linux-arm64/bindings.node
z2m        |     at bindings (/usr/src/app/node_modules/bindings/bindings.js:126:9)
z2m        |     at Object.<anonymous> (/usr/src/app/node_modules/@serialport/bindings/lib/linux.js:2:36)
z2m        |     at Module._compile (node:internal/modules/cjs/loader:1092:14)
z2m        |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
z2m        |     at Module.load (node:internal/modules/cjs/loader:972:32)
z2m        |     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
z2m        |     at Module.require (node:internal/modules/cjs/loader:996:19)
z2m        |     at require (node:internal/modules/cjs/helpers:92:18)
z2m        |     at Object.<anonymous> (/usr/src/app/node_modules/@serialport/bindings/lib/index.js:14:22)
z2m        |     at Module._compile (node:internal/modules/cjs/loader:1092:14) {
z2m        |   tries: [
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/build/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/build/Debug/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/build/Release/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/out/Debug/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/Debug/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/out/Release/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/Release/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/build/default/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/compiled/15.11.0/linux/arm64/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node',
z2m        |     '/usr/src/app/node_modules/@serialport/bindings/lib/binding/node-v88-linux-arm64/bindings.node'
z2m        |   ]
z2m        | }
```

I solved this by deleting the existing container and re-creating it. I also deleted the `store/.config-db` directory just in case.

**Comment by robertsLando** [comment]
Hummm don't think it's something wrong on my side, could be something docker related. @AlCalzone any clue?

**Comment by AlCalzone** [comment]
Judging from the logs, the yarn install does quite a bit more than just install the config package - maybe the yarn.lock is out of date?
Also there are socket timeouts, which certainly doesn't help.

**Comment by kickouille** [comment]
Hello,

Also having the same problem while running latest docker image:

```
INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```

Seeing a lot of activity with this command:

`node /opt/yarn-v1.22.5/bin/yarn.js install --production`

I had to increase disk space space and swap on a Raspberry for it not to crash by the way, but that is my problem, unless it is abnormal that this process takes up more that 1Go?

Also noticed that no `store/.config-db` folder is not created, does that happen only if the process is successful?

Regards,

Yanik

**Comment by kickouille** [comment]
Also tried solution proposed by @kpine but that doesn't seem to help on my end (delete the container, recreate it, except that I don't have the `store/.config-db` in my volume, not sure why.
hassio-addon users also opened hassio-addons/addon-zwavejs2mqtt#156 for the similar problem.

**Comment by mwav3** [comment]
There was a problem with this config directory before but that issue was fixed in a prior release - https://github.com/zwave-js/zwavejs2mqtt/issues/1122 .  This issue is new to 4.5.1 and this PR appears to have caused it by moving this config directory around - https://github.com/zwave-js/zwavejs2mqtt/pull/1294 .  The PR mentions /config should it be /.config-db  instead?  I'm in a bit over my head but there appears to be a problem relating to referencing the location of the config directory somehow.

**Comment by kpine** [comment]
`.config-db` and `config` are two different directories with different purposes. The former is the location of the external device database, the later is for user configurations.

https://zwave-js.github.io/node-zwave-js/#/usage/external-config?id=specifying-an-external-config-db-location

**Comment by kickouille** [comment]
Indeed, but `.config-db` should end up in `config` following documentation's logic.
I changed my docker-compose file to force this but that doesn't seem to help:

```
version: '3.3'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=xxx
      - TZ=Europe/Zurich 
      - NETWORK_KEY=xxx
      - STORE_DIR = /usr/src/app/store
      - ZWAVEJS_EXTERNAL_CONFIG = /usr/src/app/store/.config-db
    network_mode: host
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3001:3001' # port for zwave-js websocket server
```

**Comment by kpine** [comment]
Your STORE_DIR and ZWAVEJS_EXTERNAL_CONFIG environment variables have spaces in them, are you sure that works? You shouldn't need to set them anyways since you're using the default values. However, now that I've said that, I see my store directory no longer has `.config-db` since I've deleted it.

The result is a `store/.config-db` and `store/config`.

**Comment by kickouille** [comment]
Sorry it was a wrong copy/paste for the space.

I went one step further and tried to create `.config-db` within `store` manually and it gets populated when recreating the container. So the first problem is that this directory is not created if it doesn't exist.

```
pi@raspberrypi:~/zwavejs2mqtt/store/.config-db $ ls -all
total 144
drwxr-xr-x   3 root root  4096 Jun  4 16:18 .
drwxr-xr-x   6 root root  4096 Jun  4 16:36 ..
-rw-r--r--   1 root root 23866 Jun  4 16:18 deviceClasses.json
drwxr-xr-x 339 root root 12288 Jun  4 16:19 devices
-rw-r--r--   1 root root  6207 Jun  4 16:18 indicators.json
-rw-r--r--   1 root root 24892 Jun  4 16:18 manufacturers.json
-rw-r--r--   1 root root   715 Jun  4 16:18 meters.json
-rw-r--r--   1 root root 33785 Jun  4 16:18 notifications.json
-rw-r--r--   1 root root   214 Jun  4 16:18 scales.json
-rw-r--r--   1 root root 13268 Jun  4 16:18 sensorTypes.json
-rw-r--r--   1 root root     5 Jun  4 16:18 version
```

`store/config` doesn't exist, all config is at the root of `store`

However, update process still doesn't seem to work as these files are not updated, and I still get the same error.

**Comment by kpine** [comment]
I think you need to create the `config` directory manually. The `.config-db` directory is [supposed to be](https://github.com/zwave-js/node-zwave-js/issues/2602) created automatically, so I'm not sure what's going on there.

**Comment by kickouille** [comment]
`/usr/src/app/store` is the config directory, it is mapped to a local directory on my machine `./store` relative to where I execute the docker-compose cmds, and the installation works perfectly.
What doesn't is that the folder `./store/.config-db` for instance `/usr/src/app/store/.config-db` within the container following the mapping is not created.
I had to create it manually and then it gets populated, kind of proof that it is where it is supposed to be.

However that doesn't fix the update process, I still get the same two logs, the files are not updated and the GUI keeps telling me that there is the update available:

```
INFO ZWAVE: Calling api installConfigUpdate with args: [ [length]: 0 ]
INFO ZWAVE: Success zwave api call installConfigUpdate { success: true, message: 'Success zwave api call', result: false }
```

**Comment by kickouille** [comment]
Isn't it how the folder structure should be?

```
store/
├── .config-db
│   ├── deviceClasses.json
│   ├── devices
│   ├── indicators.json
│   ├── manufacturers.json
│   ├── meters.json
│   ├── notifications.json
│   ├── scales.json
│   ├── sensorTypes.json
│   └── version
├── xxx.json
├── xxx.metadata.jsonl
├── xxx.metadata.jsonl.lock
├── xxx.values.jsonl
├── xxx.values.jsonl.lock
├── nodes.json
├── sessions
├── settings.json
└── users.json
```

**Comment by kpine** [comment]
> `/usr/src/app/store` is the config directory, it is mapped to a local directory on my machine `./store` relative to where I execute the docker-compose cmds, and the installation works perfectly.

You are mixing up terminology. Using the default `STORE_DIR` value of `/usr/src/app/store` gives the following?

`/usr/src/app/store` is the **STORE** directory.
`/usr/src/app/store/.config-db` is the [**external config database**](https://zwave-js.github.io/node-zwave-js/#/usage/external-config) directory. This is configured with the node-zwave-js env var `ZWAVEJS_EXTERNAL_CONFIG`.
`/usr/src/app/store/config` is the [**`deviceConfigPriorityDir`**](https://zwave-js.github.io/node-zwave-js/#/api/driver?id=zwaveoptions) directory, for custom config files.

See these docs as well. <https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars>

**Comment by kickouille** [comment]
I created `/usr/src/app/store/config', recreated it all, but it is empty, update process is still failing, and even though I read the doc I still don't see the point of having this `/usr/src/app/store/config` how it could help in that precise case or what should go in there, or at least I don't need it for my usage.
Apart from that the solution is working like a charm.

**Comment by kpine** [comment]
The `config` directory has nothing to do with this issue. The purpose of that directory is to install your own custom device config files.

**Comment by kickouille** [comment]
Alright, indeed that was a bit confusing, and that makes sense nnow for this `config` directory to be created manually.

But I confirm `.config-db` is not created automatically anyway, so there must be something wrong, maybe in correlation with the upgrade process failing, even though I created it manually and got populated on the first container start.

**Comment by kpine** [comment]
I don't really think the problem of creating the `.config-db` is relevant here. When I ran into this issue I had already created the directory manually and it was populated. I deleted it "just in case", and noticed it was not being re-created. I have submitted a separate [issue](https://github.com/zwave-js/node-zwave-js/issues/2777) for that.

**Comment by mwav3** [comment]
Here's my logs if they help at all 

```
2021-06-04T18:58:12.105Z DRIVER   Config update failed: Package manager exited with code 1
                                  warning Resolution field "@zwave-js/config@7.7.2-20210602" is incompatible wit
                                  h requested version "@zwave-js/config@7.7.1"
                                  warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || 
                                  ^5.0.0".
                                  warning "prettier-standard > prettierx > @typescript-eslint/typescript-estree 
                                  > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-de
                                  v || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-
                                  beta || >= 3.7.0-dev || >= 3.7.0-beta".
                                  error /usr/src/app/node_modules/@serialport/bindings: Command failed.
                                  Exit code: 1
                                  Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebui
                                  ld
                                  Arguments: 
                                  Directory: /usr/src/app/node_modules/@serialport/bindings
                                  Output:
                                  prebuild-install WARN install No prebuilt binaries found (target=15.11.0 runti
                                  me=node arch=x64 libc=musl platform=linux)
                                  gyp info it worked if it ends with ok
                                  gyp info using node-gyp@7.1.2
                                  gyp info using node@15.11.0 | linux | x64
                                  gyp ERR! find Python 
                                  gyp ERR! find Python Python is not set from command line or npm configuration
                                  gyp ERR! find Python Python is not set from environment variable PYTHON
                                  gyp ERR! find Python checking if "python3" can be used
                                  gyp ERR! find Python - "python3" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python" can be used
                                  gyp ERR! find Python - "python" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python2" can be used
                                  gyp ERR! find Python - "python2" is not in PATH or produced an error
                                  gyp ERR! find Python 
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python You need to install the latest version of Python.
                                  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
                                  gyp ERR! find Python you can try one of the following options:
                                  gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
                                  gyp ERR! find Python   (accepted by both node-gyp and npm)
                                  gyp ERR! find Python - Set the environment variable PYTHON
                                  gyp ERR! find Python - Set the npm configuration variable python:
                                  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
                                  gyp ERR! find Python For more information consult the documentation at:
                                  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python 
                                  gyp ERR! configure error 
                                  gyp ERR! stack Error: Could not find any Python installation to use
                                  gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_
                                  modules/node-gyp/lib/find-python.js:302:47)
                                  gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/
                                  node_modules/node-gyp/lib/find-python.js:136:21)
                                  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/np
                                  m/node_modules/node-gyp/lib/find-python.js:179:16)
                                  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modul
                                  es/npm/node_modules/node-gyp/lib/find-python.js:266:16)
                                  gyp ERR! stack     at exithandler (node:child_process:333:5)
                                  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
                                  gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
                                  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child
                                  _process:288:12)
                                  gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
                                  gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_qu
                                  eues:81:21)
                                  gyp ERR! System Linux 5.8.0-50-generic
                                  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_m
                                  odules/node-gyp/bin/node-gyp.js" "rebuild"
                                  gyp ERR! cwd /usr/src/app/node_modules/@serialport/bindings
                                  gyp ERR! node -v v15.11.0
                                  gyp ERR! node-gyp -v v7.1.2
                                  gyp ERR! not ok
```

**Comment by kpine** [comment]
For some reason it's trying to install node serialport. There's no binary release for ARM platforms so it installs from source, which requires some development packages to build, and also takes some time.

**Comment by kpine** [comment]
FYI, I got the same serialport build error on my amd64 VM (not arm) instead of the socket timeout, so not really a platform issue.

**Comment by AlCalzone** [comment]
> The `.config-db` directory is [supposed to be](https://github.com/zwave-js/node-zwave-js/issues/2602) created automatically, so I'm not sure what's going on there.

Fixed in node-zwave-js 7.7.2

**Comment by kickouille** [comment]
Hello, latest version of docker image is not requesting update so I presume it comes with the latest db built in. Let’s see how it goes with next update.

**Comment by smizles** [comment]
I'm late to the conversation here (sorry if I'm not help), but I noticed I get the update notification in Z-Wave JS to MQTT add-on that advertises zwave-js version 7.7.2-20210602. However, I just checked my Z-Wave JS add-on, and I'm already running version 0.1.25, which is supposed to include the newer zwave-js version 7.7.3 according to the changelog. Could this update notification bug be related to the Zwavejs2MQTT supervisor not getting the current version from the Z-Wave JS daemon? 
![20210609_140738](https://user-images.githubusercontent.com/25838538/121409260-4993c900-c92f-11eb-96ab-eb8c133ba184.jpg)
![20210609_143200](https://user-images.githubusercontent.com/25838538/121409432-82cc3900-c92f-11eb-8ac6-f68027d5337b.jpg)
![20210609_143151](https://user-images.githubusercontent.com/25838538/121409436-8364cf80-c92f-11eb-8ea5-e7170d98f491.jpg)
![20210609_143136](https://user-images.githubusercontent.com/25838538/121409439-8495fc80-c92f-11eb-9a07-09c4c6b2cf07.jpg)

**Comment by kpine** [comment]
The Z-Wave JS Addon is not the same thing as the zwavejs2mqtt. You are looking at two different things.

**Comment by robertsLando** [comment]
Is this still failing in 5.0.0?

**Comment by kpine** [comment]
There aren't any new config updates since 7.7.3, so it's not possible to check yet. Are there changes somewhere that you expect to have fixed it?

**Comment by robertsLando** [comment]
> Are there changes somewhere that you expect to have fixed it?

Humm nope, at least not on my side

**Comment by kpine** [comment]
Ok, I guess we'll have to wait for a new update. :)

**Comment by kpine** [comment]
Still a problem in zwavejs2mqtt 5.1.0. The log message from the driver debug logs shows:

```
2021-06-24T15:28:22.924Z DRIVER   Config update failed: Package manager exited with code 1
                                  warning Resolution field "@zwave-js/config@7.9.1-20210624" is incompatible wit
                                  h requested version "@zwave-js/config@7.9.0"
                                  error https://registry.yarnpkg.com/rxjs/-/rxjs-6.6.7.tgz: ESOCKETTIMEDOUT
                                  error An unexpected error occurred: "https://registry.yarnpkg.com/vuetify/-/vu
                                  etify-2.5.3.tgz: ESOCKETTIMEDOUT".
```

I ran a second time and got a slightly different error.
```
2021-06-24T15:37:34.573Z DRIVER   Config update failed: Package manager exited with code 1
                                  warning Resolution field "@zwave-js/config@7.9.1-20210624" is incompatible wit
                                  h requested version "@zwave-js/config@7.9.0"
                                  warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 ||
                                  ^5.0.0".
                                  error /usr/src/app/node_modules/@serialport/bindings: Command failed.
                                  Exit code: 1
                                  Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebui
                                  ld
                                  Arguments:
                                  Directory: /usr/src/app/node_modules/@serialport/bindings
                                  Output:
                                  prebuild-install WARN install No prebuilt binaries found (target=16.3.0 runtim
                                  e=node arch=arm64 libc=musl platform=linux)
                                  gyp info it worked if it ends with ok
                                  gyp info using node-gyp@7.1.2
                                  gyp info using node@16.3.0 | linux | arm64
                                  gyp ERR! find Python
                                  gyp ERR! find Python Python is not set from command line or npm configuration
                                  gyp ERR! find Python Python is not set from environment variable PYTHON
                                  gyp ERR! find Python checking if "python3" can be used
                                  gyp ERR! find Python - "python3" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python" can be used
                                  gyp ERR! find Python - "python" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python2" can be used
                                  gyp ERR! find Python - "python2" is not in PATH or produced an error
                                  gyp ERR! find Python
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python You need to install the latest version of Python.
                                  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
                                  gyp ERR! find Python you can try one of the following options:
                                  gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
                                  gyp ERR! find Python   (accepted by both node-gyp and npm)
                                  gyp ERR! find Python - Set the environment variable PYTHON
                                  gyp ERR! find Python - Set the npm configuration variable python:
                                  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
                                  gyp ERR! find Python For more information consult the documentation at:
                                  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python
                                  gyp ERR! configure error
                                  gyp ERR! stack Error: Could not find any Python installation to use
                                  gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_
                                  modules/node-gyp/lib/find-python.js:302:47)
                                  gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/
                                  node_modules/node-gyp/lib/find-python.js:136:21)
                                  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/np
                                  m/node_modules/node-gyp/lib/find-python.js:179:16)
                                  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modul
                                  es/npm/node_modules/node-gyp/lib/find-python.js:266:16)
                                  gyp ERR! stack     at exithandler (node:child_process:333:5)
                                  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
                                  gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
                                  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child
                                  _process:288:12)
                                  gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
                                  gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_qu
                                  eues:83:21)
                                  gyp ERR! System Linux 5.10.17-v8+
                                  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_m
                                  odules/node-gyp/bin/node-gyp.js" "rebuild"
                                  gyp ERR! cwd /usr/src/app/node_modules/@serialport/bindings
                                  gyp ERR! node -v v16.3.0
                                  gyp ERR! node-gyp -v v7.1.2
                                  gyp ERR! not ok
```

My question from earlier remains unanswered: why is a config update requiring a new installation of node serialport? On ARM platforms this must be built from source because there are no pre-built binaries. This is probably one explanation as to why the update takes so long, and also makes the system unresponsive during the update time. I'm wondering if there's something specifically weird with ARM installations. Can a log file be used to capture the output of the yarn command, I could not find one.

**Comment by robertsLando** [comment]
> why is a config update requiring a new installation of node serialport

I have this question too, yarn/npm package resolution is really weird. Also serialport had a bug that forced me to use resolutions in package.json so maybe the methof used to install the config update breaks resolution someway? cc @AlCalzone

**Comment by AlCalzone** [comment]
I don't see how `"resolutions"` would break that - after all, it forces `yarn` to use a specific version which is already installed.

If anyone wants to investigate, you could do the steps manually:
1. navigate to the folder `/usr/src/app`
2. edit `package.json` and add this in `"resolutions"`: `"@zwave-js/config": "7.9.1-20210624"`
3. run `yarn install --verbose`

**Comment by AlCalzone** [comment]
Also: why is everything related to Docker so annoying?

**Comment by kpine** [comment]
Here's a log from my RPi4.  [yarn.log](https://github.com/zwave-js/zwavejs2mqtt/files/6712320/yarn.log)

**Comment by AlCalzone** [comment]
Okay, that is re-installing **everything** 🤔

**Comment by AlCalzone** [comment]
@kpine can you do the same again, but with `yarn install --production --verbose`?

**Comment by mamoel666** [comment]
Same problem here since updating to 5.1.0:

```
2021-06-25T09:19:37.186Z DRIVER   Config update failed: Package manager exited with code 1
                                  warning Resolution field "@zwave-js/config@7.9.1-20210625" is incompatible wit
                                  h requested version "@zwave-js/config@7.9.0"
                                  warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || 
                                  ^5.0.0".
                                  error /usr/src/app/node_modules/@serialport/bindings: Command failed.
                                  Exit code: 1
                                  Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebui
                                  ld
                                  Arguments: 
                                  Directory: /usr/src/app/node_modules/@serialport/bindings
                                  Output:
                                  prebuild-install WARN install No prebuilt binaries found (target=16.3.0 runtim
                                  e=node arch=x64 libc=musl platform=linux)
                                  gyp info it worked if it ends with ok
                                  gyp info using node-gyp@7.1.2
                                  gyp info using node@16.3.0 | linux | x64
                                  gyp ERR! find Python 
                                  gyp ERR! find Python Python is not set from command line or npm configuration
                                  gyp ERR! find Python Python is not set from environment variable PYTHON
                                  gyp ERR! find Python checking if "python3" can be used
                                  gyp ERR! find Python - "python3" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python" can be used
                                  gyp ERR! find Python - "python" is not in PATH or produced an error
                                  gyp ERR! find Python checking if "python2" can be used
                                  gyp ERR! find Python - "python2" is not in PATH or produced an error
                                  gyp ERR! find Python 
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python You need to install the latest version of Python.
                                  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
                                  gyp ERR! find Python you can try one of the following options:
                                  gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
                                  gyp ERR! find Python   (accepted by both node-gyp and npm)
                                  gyp ERR! find Python - Set the environment variable PYTHON
                                  gyp ERR! find Python - Set the npm configuration variable python:
                                  gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
                                  gyp ERR! find Python For more information consult the documentation at:
                                  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
                                  gyp ERR! find Python *********************************************************
                                  *
                                  gyp ERR! find Python 
                                  gyp ERR! configure error 
                                  gyp ERR! stack Error: Could not find any Python installation to use
                                  gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_
                                  modules/node-gyp/lib/find-python.js:302:47)
                                  gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/
                                  node_modules/node-gyp/lib/find-python.js:136:21)
                                  gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/np
                                  m/node_modules/node-gyp/lib/find-python.js:179:16)
                                  gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modul
                                  es/npm/node_modules/node-gyp/lib/find-python.js:266:16)
                                  gyp ERR! stack     at exithandler (node:child_process:333:5)
                                  gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
                                  gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
                                  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child
                                  _process:288:12)
                                  gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
                                  gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_qu
                                  eues:83:21)
                                  gyp ERR! System Linux 4.4.59+
                                  gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_m
                                  odules/node-gyp/bin/node-gyp.js" "rebuild"
                                  gyp ERR! cwd /usr/src/app/node_modules/@serialport/bindings
                                  gyp ERR! node -v v16.3.0
                                  gyp ERR! node-gyp -v v7.1.2
                                  gyp ERR! not ok
```

**Comment by robertsLando** [comment]
Docker magic

**Comment by kpine** [comment]
> yarn install --production --verbose

```
bash-5.0# yarn install --production --verbose |& tee /tmp/yarn-production.log
yarn install v1.22.5
...
```
Doesn't seem to have made much difference (?), still looks like it's installing the entire world. I used `@zwave-js/config@7.9.1-20210625` today.

[yarn-production.log](https://github.com/zwave-js/zwavejs2mqtt/files/6717364/yarn-production.log)

**Comment by AlCalzone** [comment]
Ok I suspect this has to do with how zwavejs2mqtt is installed in the container. I did a test on my Raspberry Pi:
1. create and enter empty directory
2. `yarn init`, confirm everything
3. `yarn add zwave-js`
4. edit `package.json` like above
5. `yarn install --production`

The log looks like this:
```
[1/4] Resolving packages...
verbose 1.907421241 Performing "GET" request to "https://registry.npmjs.org/@zwave-js%2fconfig".
verbose 2.344177515 Request "https://registry.npmjs.org/@zwave-js%2fconfig" finished with status code 200.
warning Resolution field "@zwave-js/config@7.9.1-20210625" is incompatible with requested version "@zwave-js/config@7.9.0"
[2/4] Fetching packages...
verbose 3.068732471 Performing "GET" request to "https://registry.yarnpkg.com/@zwave-js/config/-/config-7.9.1-20210625.tgz".
[3/4] Linking dependencies...
... a lot of stuff about skipped files ...
```

--> only `@zwave-js/config` is downloaded and installed.

**Comment by kpine** [comment]
Try deleting `/usr/local/share/.cache` between steps 3 and 5.

Looks like yarn will re-download and then re-install everything when the cache is missing. Because of the docker multistage build, the cache directory is not populated in the final image, so apparently this causes the full re-install. As a test I updated the Dockerfile to copy the cache directory. When I repeat the manual steps (add resolution to package.json, `yarn install --production`) it only does a single GET for the config package, and everything installs quickly, just as you did.

```diff
diff --git a/docker/Dockerfile b/docker/Dockerfile
index ad3971e..edba3e8 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -55,6 +55,7 @@ RUN apk add --no-cache \

 # Copy files from previous build stage
 COPY --from=build-z2m /usr/src/app /usr/src/app
+COPY --from=build-z2m /usr/local/share/.cache /usr/local/share/.cache

 ENV ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
```

Including the 500+ MB cache directory in the image explodes the image size more than 2x, so unless there are no other means I wouldn't call it a solution.

**Comment by AlCalzone** [comment]
Ugh - guess I'll have to do the package manager's job myself after all. Download the tarball and unpack it in the correct location that is...

**Comment by thecobra666** [comment]
> Same problem here since updating to 5.1.0 (Docker, Synology DS418play):
> 
> ```
> 2021-06-25T09:19:37.186Z DRIVER   Config update failed: Package manager exited with code 1
>                                   warning Resolution field "@zwave-js/config@7.9.1-20210625" is incompatible wit
>                                   h requested version "@zwave-js/config@7.9.0"
>                                   warning " > eslint-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || 
>                                   ^5.0.0".
>                                   error /usr/src/app/node_modules/@serialport/bindings: Command failed.
>                                   Exit code: 1
>                                   Command: prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebui
>                                   ld
>                                   Arguments: 
>                                   Directory: /usr/src/app/node_modules/@serialport/bindings
>                                   Output:
>                                   prebuild-install WARN install No prebuilt binaries found (target=16.3.0 runtim
>                                   e=node arch=x64 libc=musl platform=linux)
>                                   gyp info it worked if it ends with ok
>                                   gyp info using node-gyp@7.1.2
>                                   gyp info using node@16.3.0 | linux | x64
>                                   gyp ERR! find Python 
>                                   gyp ERR! find Python Python is not set from command line or npm configuration
>                                   gyp ERR! find Python Python is not set from environment variable PYTHON
>                                   gyp ERR! find Python checking if "python3" can be used
>                                   gyp ERR! find Python - "python3" is not in PATH or produced an error
>                                   gyp ERR! find Python checking if "python" can be used
>                                   gyp ERR! find Python - "python" is not in PATH or produced an error
>                                   gyp ERR! find Python checking if "python2" can be used
>                                   gyp ERR! find Python - "python2" is not in PATH or produced an error
>                                   gyp ERR! find Python 
>                                   gyp ERR! find Python *********************************************************
>                                   *
>                                   gyp ERR! find Python You need to install the latest version of Python.
>                                   gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
>                                   gyp ERR! find Python you can try one of the following options:
>                                   gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
>                                   gyp ERR! find Python   (accepted by both node-gyp and npm)
>                                   gyp ERR! find Python - Set the environment variable PYTHON
>                                   gyp ERR! find Python - Set the npm configuration variable python:
>                                   gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
>                                   gyp ERR! find Python For more information consult the documentation at:
>                                   gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
>                                   gyp ERR! find Python *********************************************************
>                                   *
>                                   gyp ERR! find Python 
>                                   gyp ERR! configure error 
>                                   gyp ERR! stack Error: Could not find any Python installation to use
>                                   gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_
>                                   modules/node-gyp/lib/find-python.js:302:47)
>                                   gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/
>                                   node_modules/node-gyp/lib/find-python.js:136:21)
>                                   gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/np
>                                   m/node_modules/node-gyp/lib/find-python.js:179:16)
>                                   gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modul
>                                   es/npm/node_modules/node-gyp/lib/find-python.js:266:16)
>                                   gyp ERR! stack     at exithandler (node:child_process:333:5)
>                                   gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
>                                   gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
>                                   gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child
>                                   _process:288:12)
>                                   gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
>                                   gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_qu
>                                   eues:83:21)
>                                   gyp ERR! System Linux 4.4.59+
>                                   gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_m
>                                   odules/node-gyp/bin/node-gyp.js" "rebuild"
>                                   gyp ERR! cwd /usr/src/app/node_modules/@serialport/bindings
>                                   gyp ERR! node -v v16.3.0
>                                   gyp ERR! node-gyp -v v7.1.2
>                                   gyp ERR! not ok
> ```

Same here. I don't want to do custom fiddling with this since it's way to important.. will this be fixed in update?
